In [4]:
# import pprint as pp
import numpy as np
import scipy.linalg as sc
A= np.array([[0.80,0.20],[0.30,0.70]])
P, L, U = sc.lu(A)

print ("A:\n",A)
# pp.pprint(A)

print ("P:\n",P)
# pp.pprint(P)

print ("L:\n",L)
# pp.pprint(L)

print ("U:\n",U)
# pp.pprint(U)


A:
 [[0.8 0.2]
 [0.3 0.7]]
P:
 [[1. 0.]
 [0. 1.]]
L:
 [[1.    0.   ]
 [0.375 1.   ]]
U:
 [[0.8   0.2  ]
 [0.    0.625]]


In [5]:
A = np.array([[0.80,0.20],[0.30,0.70] ])
P, L, U = sc.lu(A)

print ("A:\n",A)
# pp.pprint(A)

print ("P\n:",P)
# pp.pprint(P)

print ("L:\n",L)
# pp.pprint(L)

print ("U:\n",U)
# pp.pprint(U)

A:
 [[0.8 0.2]
 [0.3 0.7]]
P
: [[1. 0.]
 [0. 1.]]
L:
 [[1.    0.   ]
 [0.375 1.   ]]
U:
 [[0.8   0.2  ]
 [0.    0.625]]


In [6]:
# import pprint as pp
import numpy as np
import scipy.linalg as sc
A = np.array([[0.80,0.20],[0.30,0.70]])
B = np.array([[0], [0]])
P, L, U = sc.lu(A)

print ("A:\n",A)
print("B:\n",B)
# pp.pprint(A)

print("True or false? A=PLU\n", A==P@(L@U))

print ("P:\n",P)
# pp.pprint(P)

print ("L:\n",L)
# pp.pprint(L)

print ("U:\n",U)
# pp.pprint(U)

A:
 [[0.8 0.2]
 [0.3 0.7]]
B:
 [[0]
 [0]]
True or false? A=PLU
 [[ True  True]
 [ True  True]]
P:
 [[1. 0.]
 [0. 1.]]
L:
 [[1.    0.   ]
 [0.375 1.   ]]
U:
 [[0.8   0.2  ]
 [0.    0.625]]


In [8]:
def forward_substitution(L, b):



   #Get number of rows

   n = L.shape[0]



   #Allocating space for the solution vector

   y = np.zeros_like(b, dtype=np.double);



   #Here we perform the forward-substitution. 

   #Initializing with the first row.

   y[0] = b[0] / L[0, 0]



   #Looping over rows in reverse (from the bottom up),

   #starting with the second to last row, because the 

   #last row solve was completed in the last step.

   for i in range(1, n):

       y[i] = (b[i] - np.dot(L[i,:i], y[:i])) / L[i,i]



   return y



def back_substitution(U, y):



   #Number of rows

   n = U.shape[0]



   #Allocating space for the solution vector

   x = np.zeros_like(y, dtype=np.double);



   #Here we perform the back-substitution. 

   #Initializing with the last row.

   x[-1] = y[-1] / U[-1, -1]



   #Looping over rows in reverse (from the bottom up), 

   #starting with the second to last row, because the 

   #last row solve was completed in the last step.

   for i in range(n-2, -1, -1):

       x[i] = (y[i] - np.dot(U[i,i:], x[i:])) / U[i,i]



   return x

In [9]:
A = np.array([[0.80,0.20],[0.30,0.70]])
B = np.array([[0], [0]])
# P, L, U = sc.lu(A)

print ("A:\n",A)
print("B:\n",B)
# pp.pprint(A)

print("True or false? A=PLU\n", A==P@(L@U))

# print ("P:\n",P)
# # pp.pprint(P)

# print ("L:\n",L)
# # pp.pprint(L)

# print ("U:\n",U)
# # pp.pprint(U)

trabsPB = np.transpose(P)
y = forward_substitution(L, trabsPB)
x = back_substitution(U, y)
print("x = ",x)

print("Comparing to the Numpy np.linalf.solve function")
u = sc.solve(A,B)

A:
 [[0.8 0.2]
 [0.3 0.7]]
B:
 [[0]
 [0]]
True or false? A=PLU
 [[ True  True]
 [ True  True]]
x =  [[ 1.4 -0.4]
 [-0.6  1.6]]
Comparing to the Numpy np.linalf.solve function
